# Test your FastAPI endpoints

###
# test with no version
GET http://127.0.0.1:8000/provision?token=CVFedarGsdfvtrshDARFBGstrf&mac=7c8d9c14ec12
Accept: application/json

###

PUT http://127.0.0.1:8000/state?mac=7c8d9c1f7a6e&state=balls
Accept: application/json

###
# test successful return of newest version
GET https://192.168.80.110/provision
Accept: application/json

###
# test successful return of newest version
GET http://38.126.155.75/provision?mac=7c8d9c14ec12
Accept: application/json

###
# test successful return of newest version
GET https://firmware.itops.io/provision?mac=7c8d9c1f7a6e
Accept: application/json

###
# test successful return of newest version
PUT https://firmware.itops.io/state
Accept: application/json